name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          # just perform install
          runTests: false
      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          # we have already installed all dependencies above
          install: false
          # Cypress tests and config file are in "e2e" folder
          working-directory: cypress/e2e

      - name: Download the build folders
        if: ${{ failure() }}  # Run the step only if there was a failure
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
