name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: false

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
  
      - name: Install dependencies cypress
        uses: cypress-io/github-action@v5
        with:
          # just perform install
          runTests: false
      
      - run: yarn lint

      - name: Clone Cypress RealWorld App
        run: git clone https://github.com/cypress-io/cypress-realworld-app

      - name: Install Dependencies Cypress RealWorld App
        run: yarn install
        working-directory: cypress-realworld-app
      
      - name: Run Cypress RealWorld App
        run: |
          yarn dev &
          while ! nc -z localhost 3000; do sleep 1; done
          echo "Cypress RealWorld App is up and running"
        working-directory: cypress-realworld-app

      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          # we have already installed all dependencies above
          install: false
          working-directory: e2e

      - name: Setup tmate session for debugging
        if: ${{ failure() && env.ACTIONS_RUNNER_DEBUG == 'true' }}
        uses: mxschmitt/action-tmate@v3

      - name: Download the build folders
        if: ${{ failure() }}  # Run the step only if there was a failure
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: videos
