name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Install dependencies cypress
        uses: cypress-io/github-action@v5
        with:
          # just perform install
          runTests: false
      
      - run: yarn lint

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          # we have already installed all dependencies above
          install: false
          working-directory: e2e

      - name: Download the build folders
        if: ${{ failure() }}  # Run the step only if there was a failure
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: videos
