# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Clone Cypress RealWorld App
      run: git clone https://github.com/cypress-io/cypress-realworld-app

    - name: Install Dependencies Cypress RealWorld App
      run: yarn install
      working-directory: cypress-realworld-app

    - name: Build and Start Project Cypress RealWorld App
      run: yarn run dev &
      working-directory: cypress-realworld-app

    - name: Wait for Port 3000 to be Available
      run: |
        while ! nc -z localhost 3000; do
          sleep 1
        done

    - run: yarn install
    - run: yarn run test
